// Copyright 2013-2026 go-diameter authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"strings"
	"unicode"

	"github.com/fiorix/go-diameter/v4/diam/dict"
)

// runtimeImport is the shared runtime package the generated code depends on.
const runtimeImport = "github.com/fiorix/go-diameter/v4/staticodec"

// header returns the file preamble for an application package. withImport
// adds the staticodec runtime import (needed by everything except enums).
func header(app *application, withImport bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by staticodegen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source of truth: dictionary XML under diam/dict/testdata, filtered by\n")
	fmt.Fprintf(&b, "// the allowlist in cmd/staticodegen/model.go.\n\n")
	fmt.Fprintf(&b, "package %s\n", app.pkg)
	if withImport {
		fmt.Fprintf(&b, "\nimport %q\n", runtimeImport)
	}
	return b.String()
}

// ownershipDoc is stamped on every generated type (codec-design.md §2.5).
const ownershipDoc = `//
// OWNERSHIP: all []byte fields (including staticodec.RawAVP data) alias the
// read buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.`

func gofmt(src []byte) []byte {
	out, err := format.Source(src)
	if err != nil {
		log.Fatalf("generated code does not parse: %v\n%s", err, src)
	}
	return out
}

// goType returns the Go field type for a resolved field.
func goType(f *field) string {
	var t string
	switch f.kind {
	case kindU32, kindTime:
		t = "uint32"
	case kindU64:
		t = "uint64"
	case kindEnum:
		t = "int32"
	case kindBytes:
		t = "[]byte"
	case kindGroup:
		t = f.group
	}
	if f.repeated {
		return "[]" + t
	}
	return t
}

// hasFlag reports whether the field needs a sidecar Has<Name> bool:
// scalars and single groups do; slices and []byte use emptiness/nil.
func hasFlag(f *field) bool {
	if f.repeated || f.kind == kindBytes {
		return false
	}
	return true
}

// avpComment renders "Name (code[, vendor V])" for generated case labels.
func avpComment(f *field) string {
	if f.vendorID != 0 {
		return fmt.Sprintf("%s (%d, vendor %d)", f.avpName, f.code, f.vendorID)
	}
	return fmt.Sprintf("%s (%d)", f.avpName, f.code)
}

// emitStructBody writes the type declaration plus parseGroup, appendGroup,
// Reset and Clone for one structDef. Message-level wrappers are emitted
// separately by emitMessage.
func emitStructBody(w *bytes.Buffer, s *structDef, isMessage bool) {
	fmt.Fprintf(w, "// %s\n%s\n", s.doc, ownershipDoc)
	fmt.Fprintf(w, "type %s struct {\n", s.name)
	if isMessage {
		fmt.Fprintf(w, "\t// Hdr is the fixed Diameter header. ParseFrom fills it; for\n")
		fmt.Fprintf(w, "\t// hand-built messages set CommandFlags/HopByHopID/EndToEndID\n")
		fmt.Fprintf(w, "\t// before AppendTo (command code and app id are set by AppendTo).\n")
		fmt.Fprintf(w, "\tHdr staticodec.Header\n\n")
	}
	for i := range s.fields {
		f := &s.fields[i]
		fmt.Fprintf(w, "\t%s %s // %s\n", f.goName, goType(f), avpComment(f))
		if hasFlag(f) {
			fmt.Fprintf(w, "\tHas%s bool\n", f.goName)
		}
	}
	fmt.Fprintf(w, "\n\t// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit\n")
	fmt.Fprintf(w, "\t// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED\n")
	fmt.Fprintf(w, "\t// with Failed-AVP; entries also appear in Other.\n")
	fmt.Fprintf(w, "\tUnsupportedMandatory []staticodec.RawAVP\n")
	fmt.Fprintf(w, "\t// Other preserves all unknown AVPs in arrival order; AppendTo\n")
	fmt.Fprintf(w, "\t// re-emits them after the modeled fields.\n")
	fmt.Fprintf(w, "\tOther []staticodec.RawAVP\n")
	fmt.Fprintf(w, "}\n\n")

	emitParseGroup(w, s)
	emitAppendGroup(w, s)
	emitReset(w, s, isMessage)
	emitClone(w, s, isMessage)
}

func emitParseGroup(w *bytes.Buffer, s *structDef) {
	fmt.Fprintf(w, "// parseGroup decodes a sequence of AVPs into v. The caller must\n")
	fmt.Fprintf(w, "// have Reset() v (ParseFrom does).\n")
	fmt.Fprintf(w, "func (v *%s) parseGroup(buf []byte) error {\n", s.name)
	fmt.Fprintf(w, "\tfor off := 0; off < len(buf); {\n")
	fmt.Fprintf(w, "\t\tcode, flags, vendorID, data, next, err := staticodec.WalkAVP(buf, off)\n")
	fmt.Fprintf(w, "\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
	fmt.Fprintf(w, "\t\tswitch {\n")
	for i := range s.fields {
		f := &s.fields[i]
		fmt.Fprintf(w, "\t\tcase code == %d && vendorID == %d: // %s\n", f.code, f.vendorID, avpComment(f))
		switch f.kind {
		case kindU32, kindTime:
			fmt.Fprintf(w, "\t\t\tif len(data) != 4 {\n\t\t\t\treturn staticodec.ErrBadAVPData\n\t\t\t}\n")
			fmt.Fprintf(w, "\t\t\tv.%s = staticodec.BE32(data)\n", f.goName)
			fmt.Fprintf(w, "\t\t\tv.Has%s = true\n", f.goName)
		case kindU64:
			fmt.Fprintf(w, "\t\t\tif len(data) != 8 {\n\t\t\t\treturn staticodec.ErrBadAVPData\n\t\t\t}\n")
			fmt.Fprintf(w, "\t\t\tv.%s = staticodec.BE64(data)\n", f.goName)
			fmt.Fprintf(w, "\t\t\tv.Has%s = true\n", f.goName)
		case kindEnum:
			fmt.Fprintf(w, "\t\t\tif len(data) != 4 {\n\t\t\t\treturn staticodec.ErrBadAVPData\n\t\t\t}\n")
			if f.repeated {
				fmt.Fprintf(w, "\t\t\tv.%s = append(v.%s, int32(staticodec.BE32(data)))\n", f.goName, f.goName)
			} else {
				fmt.Fprintf(w, "\t\t\tv.%s = int32(staticodec.BE32(data))\n", f.goName)
				fmt.Fprintf(w, "\t\t\tv.Has%s = true\n", f.goName)
			}
		case kindBytes:
			if f.repeated {
				fmt.Fprintf(w, "\t\t\tv.%s = append(v.%s, data)\n", f.goName, f.goName)
			} else {
				fmt.Fprintf(w, "\t\t\tv.%s = data\n", f.goName)
			}
		case kindGroup:
			if f.repeated {
				fmt.Fprintf(w, "\t\t\tif cap(v.%s) > len(v.%s) {\n", f.goName, f.goName)
				fmt.Fprintf(w, "\t\t\t\tv.%s = v.%s[:len(v.%s)+1]\n", f.goName, f.goName, f.goName)
				fmt.Fprintf(w, "\t\t\t\tv.%s[len(v.%s)-1].Reset()\n", f.goName, f.goName)
				fmt.Fprintf(w, "\t\t\t} else {\n")
				fmt.Fprintf(w, "\t\t\t\tv.%s = append(v.%s, %s{})\n", f.goName, f.goName, f.group)
				fmt.Fprintf(w, "\t\t\t}\n")
				fmt.Fprintf(w, "\t\t\tif err := v.%s[len(v.%s)-1].parseGroup(data); err != nil {\n", f.goName, f.goName)
				fmt.Fprintf(w, "\t\t\t\treturn err\n\t\t\t}\n")
			} else {
				fmt.Fprintf(w, "\t\t\tv.%s.Reset()\n", f.goName)
				fmt.Fprintf(w, "\t\t\tif err := v.%s.parseGroup(data); err != nil {\n", f.goName)
				fmt.Fprintf(w, "\t\t\t\treturn err\n\t\t\t}\n")
				fmt.Fprintf(w, "\t\t\tv.Has%s = true\n", f.goName)
			}
		}
	}
	fmt.Fprintf(w, "\t\tdefault:\n")
	fmt.Fprintf(w, "\t\t\traw := staticodec.RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}\n")
	fmt.Fprintf(w, "\t\t\tv.Other = append(v.Other, raw)\n")
	fmt.Fprintf(w, "\t\t\tif flags&staticodec.FlagMandatory != 0 {\n")
	fmt.Fprintf(w, "\t\t\t\tv.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)\n")
	fmt.Fprintf(w, "\t\t\t}\n")
	fmt.Fprintf(w, "\t\t}\n")
	fmt.Fprintf(w, "\t\toff = next\n")
	fmt.Fprintf(w, "\t}\n\treturn nil\n}\n\n")
}

func emitAppendGroup(w *bytes.Buffer, s *structDef) {
	fmt.Fprintf(w, "// appendGroup serializes v's AVPs in the fixed emission order\n")
	fmt.Fprintf(w, "// (codec-design.md §2.6), unknown AVPs last in arrival order.\n")
	fmt.Fprintf(w, "func (v *%s) appendGroup(dst []byte) []byte {\n", s.name)
	needGOff := false
	for i := range s.fields {
		if s.fields[i].kind == kindGroup {
			needGOff = true
		}
	}
	if needGOff {
		fmt.Fprintf(w, "\tvar gOff int\n")
	}
	for i := range s.fields {
		f := &s.fields[i]
		args := fmt.Sprintf("%d, 0x%02x, %d", f.code, f.flags, f.vendorID)
		switch f.kind {
		case kindU32, kindTime:
			fmt.Fprintf(w, "\tif v.Has%s { // %s\n", f.goName, avpComment(f))
			fmt.Fprintf(w, "\t\tdst = staticodec.AppendAVPUint32(dst, %s, v.%s)\n\t}\n", args, f.goName)
		case kindU64:
			fmt.Fprintf(w, "\tif v.Has%s { // %s\n", f.goName, avpComment(f))
			fmt.Fprintf(w, "\t\tdst = staticodec.AppendAVPUint64(dst, %s, v.%s)\n\t}\n", args, f.goName)
		case kindEnum:
			if f.repeated {
				fmt.Fprintf(w, "\tfor _, e := range v.%s { // %s\n", f.goName, avpComment(f))
				fmt.Fprintf(w, "\t\tdst = staticodec.AppendAVPInt32(dst, %s, e)\n\t}\n", args)
			} else {
				fmt.Fprintf(w, "\tif v.Has%s { // %s\n", f.goName, avpComment(f))
				fmt.Fprintf(w, "\t\tdst = staticodec.AppendAVPInt32(dst, %s, v.%s)\n\t}\n", args, f.goName)
			}
		case kindBytes:
			if f.repeated {
				fmt.Fprintf(w, "\tfor _, b := range v.%s { // %s\n", f.goName, avpComment(f))
				fmt.Fprintf(w, "\t\tdst = staticodec.AppendAVPBytes(dst, %s, b)\n\t}\n", args)
			} else {
				fmt.Fprintf(w, "\tif v.%s != nil { // %s\n", f.goName, avpComment(f))
				fmt.Fprintf(w, "\t\tdst = staticodec.AppendAVPBytes(dst, %s, v.%s)\n\t}\n", args, f.goName)
			}
		case kindGroup:
			if f.repeated {
				fmt.Fprintf(w, "\tfor i := range v.%s { // %s\n", f.goName, avpComment(f))
				fmt.Fprintf(w, "\t\tdst, gOff = staticodec.OpenGroupedAVP(dst, %s)\n", args)
				fmt.Fprintf(w, "\t\tdst = v.%s[i].appendGroup(dst)\n", f.goName)
				fmt.Fprintf(w, "\t\tdst = staticodec.CloseGroupedAVP(dst, gOff)\n\t}\n")
			} else {
				fmt.Fprintf(w, "\tif v.Has%s { // %s\n", f.goName, avpComment(f))
				fmt.Fprintf(w, "\t\tdst, gOff = staticodec.OpenGroupedAVP(dst, %s)\n", args)
				fmt.Fprintf(w, "\t\tdst = v.%s.appendGroup(dst)\n", f.goName)
				fmt.Fprintf(w, "\t\tdst = staticodec.CloseGroupedAVP(dst, gOff)\n\t}\n")
			}
		}
	}
	fmt.Fprintf(w, "\tfor i := range v.Other {\n")
	fmt.Fprintf(w, "\t\tdst = v.Other[i].AppendTo(dst)\n")
	fmt.Fprintf(w, "\t}\n")
	fmt.Fprintf(w, "\treturn dst\n}\n\n")
}

func emitReset(w *bytes.Buffer, s *structDef, isMessage bool) {
	fmt.Fprintf(w, "// Reset clears v for reuse, keeping slice capacity (steady-state\n")
	fmt.Fprintf(w, "// zero-allocation parsing when the caller pools %s values).\n", s.name)
	fmt.Fprintf(w, "func (v *%s) Reset() {\n", s.name)
	if isMessage {
		fmt.Fprintf(w, "\tv.Hdr = staticodec.Header{}\n")
	}
	for i := range s.fields {
		f := &s.fields[i]
		switch {
		case f.repeated:
			fmt.Fprintf(w, "\tv.%s = v.%s[:0]\n", f.goName, f.goName)
		case f.kind == kindBytes:
			fmt.Fprintf(w, "\tv.%s = nil\n", f.goName)
		case f.kind == kindGroup:
			fmt.Fprintf(w, "\tv.%s.Reset()\n", f.goName)
			fmt.Fprintf(w, "\tv.Has%s = false\n", f.goName)
		default:
			fmt.Fprintf(w, "\tv.%s = 0\n", f.goName)
			fmt.Fprintf(w, "\tv.Has%s = false\n", f.goName)
		}
	}
	fmt.Fprintf(w, "\tv.UnsupportedMandatory = v.UnsupportedMandatory[:0]\n")
	fmt.Fprintf(w, "\tv.Other = v.Other[:0]\n")
	fmt.Fprintf(w, "}\n\n")
}

func emitClone(w *bytes.Buffer, s *structDef, isMessage bool) {
	fmt.Fprintf(w, "// Clone returns a deep copy of v whose []byte fields own their\n")
	fmt.Fprintf(w, "// backing arrays; safe to retain after the handler returns.\n")
	fmt.Fprintf(w, "func (v *%s) Clone() *%s {\n", s.name, s.name)
	fmt.Fprintf(w, "\tc := *v\n")
	_ = isMessage // Hdr is a value type; struct copy suffices
	for i := range s.fields {
		f := &s.fields[i]
		switch {
		case f.kind == kindBytes && f.repeated:
			fmt.Fprintf(w, "\tif v.%s != nil {\n", f.goName)
			fmt.Fprintf(w, "\t\tc.%s = make([][]byte, len(v.%s))\n", f.goName, f.goName)
			fmt.Fprintf(w, "\t\tfor i := range v.%s {\n", f.goName)
			fmt.Fprintf(w, "\t\t\tc.%s[i] = append([]byte(nil), v.%s[i]...)\n", f.goName, f.goName)
			fmt.Fprintf(w, "\t\t}\n\t}\n")
		case f.kind == kindBytes:
			fmt.Fprintf(w, "\tc.%s = append([]byte(nil), v.%s...)\n", f.goName, f.goName)
		case f.kind == kindGroup && f.repeated:
			fmt.Fprintf(w, "\tif v.%s != nil {\n", f.goName)
			fmt.Fprintf(w, "\t\tc.%s = make([]%s, len(v.%s))\n", f.goName, f.group, f.goName)
			fmt.Fprintf(w, "\t\tfor i := range v.%s {\n", f.goName)
			fmt.Fprintf(w, "\t\t\tc.%s[i] = *v.%s[i].Clone()\n", f.goName, f.goName)
			fmt.Fprintf(w, "\t\t}\n\t}\n")
		case f.kind == kindGroup:
			fmt.Fprintf(w, "\tc.%s = *v.%s.Clone()\n", f.goName, f.goName)
		case f.repeated: // repeated scalar ([]int32)
			fmt.Fprintf(w, "\tc.%s = append([]%s(nil), v.%s...)\n", f.goName, strings.TrimPrefix(goType(f), "[]"), f.goName)
		}
	}
	fmt.Fprintf(w, "\tc.UnsupportedMandatory = staticodec.CloneRawAVPs(v.UnsupportedMandatory)\n")
	fmt.Fprintf(w, "\tc.Other = staticodec.CloneRawAVPs(v.Other)\n")
	fmt.Fprintf(w, "\treturn &c\n}\n\n")
}

func emitGroups(app *application) []byte {
	var w bytes.Buffer
	w.WriteString(header(app, true))
	w.WriteString("\n")
	for i := range app.groups {
		emitStructBody(&w, &app.groups[i], false)
	}
	return gofmt(w.Bytes())
}

func emitMessage(app *application, m *messageDef) []byte {
	var w bytes.Buffer
	w.WriteString(header(app, true))
	w.WriteString("\n")
	emitStructBody(&w, &m.structDef, true)

	fmt.Fprintf(&w, "// ParseFrom decodes a complete Diameter message (including the\n")
	fmt.Fprintf(&w, "// 20-byte header) into m. It never panics on malformed input.\n")
	fmt.Fprintf(&w, "func (m *%s) ParseFrom(buf []byte) error {\n", m.name)
	fmt.Fprintf(&w, "\tm.Reset()\n")
	fmt.Fprintf(&w, "\th, err := staticodec.ParseHeader(buf)\n")
	fmt.Fprintf(&w, "\tif err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(&w, "\tif h.CommandCode != %d {\n\t\treturn staticodec.ErrUnexpectedCommand\n\t}\n", m.code)
	fmt.Fprintf(&w, "\tm.Hdr = h\n")
	fmt.Fprintf(&w, "\treturn m.parseGroup(buf[staticodec.HeaderLength:])\n}\n\n")

	fmt.Fprintf(&w, "// AppendTo serializes m append-style (like strconv.Append*) so the\n")
	fmt.Fprintf(&w, "// caller controls buffer reuse. Command code and application id are\n")
	fmt.Fprintf(&w, "// fixed (%d/%d); flags and hop/end ids come from m.Hdr. Message and\n", m.code, m.appID)
	fmt.Fprintf(&w, "// grouped lengths are reserve-and-backpatched in a single pass.\n")
	fmt.Fprintf(&w, "func (m *%s) AppendTo(dst []byte) []byte {\n", m.name)
	fmt.Fprintf(&w, "\tmsgOff := len(dst)\n")
	fmt.Fprintf(&w, "\th := m.Hdr\n")
	fmt.Fprintf(&w, "\th.CommandCode = %d\n", m.code)
	fmt.Fprintf(&w, "\th.ApplicationID = %d\n", m.appID)
	fmt.Fprintf(&w, "\tdst = staticodec.AppendHeader(dst, h)\n")
	fmt.Fprintf(&w, "\tdst = m.appendGroup(dst)\n")
	fmt.Fprintf(&w, "\tstaticodec.BackpatchMessageLength(dst, msgOff)\n")
	fmt.Fprintf(&w, "\treturn dst\n}\n")
	return gofmt(w.Bytes())
}

func emitEnums(app *application, avps map[string]*dict.AVP) []byte {
	var w bytes.Buffer
	w.WriteString(header(app, false))
	w.WriteString("\n// Enumerated values from the dictionary for allowlisted AVPs.\n")
	for _, ea := range app.enums {
		a, ok := avps[ea.avpName]
		if !ok {
			log.Fatalf("enums: AVP %q not found", ea.avpName)
		}
		if len(a.Data.Enum) == 0 {
			log.Fatalf("enums: AVP %q has no enumerated items", ea.avpName)
		}
		prefix := ea.prefix
		fmt.Fprintf(&w, "\n// %s (%d) values.\nconst (\n", ea.avpName, a.Code)
		seen := map[string]bool{}
		for _, e := range a.Data.Enum {
			id := prefix + mangle(e.Name)
			if seen[id] {
				continue
			}
			seen[id] = true
			fmt.Fprintf(&w, "\t%s int32 = %d\n", id, e.Code)
		}
		fmt.Fprintf(&w, ")\n")
	}
	return gofmt(w.Bytes())
}

// mangle converts a dictionary name ("CC-Request-Type", "INITIAL_REQUEST")
// into a Go identifier fragment ("CCRequestType", "InitialRequest").
func mangle(s string) string {
	var b strings.Builder
	up := true
	prevUpper := false
	for _, r := range s {
		switch {
		case r == '-' || r == '_' || r == ' ' || r == '.' || r == '/':
			up = true
			prevUpper = false
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			if b.Len() == 0 && unicode.IsDigit(r) {
				b.WriteRune('N')
			}
			switch {
			case up:
				b.WriteRune(unicode.ToUpper(r))
				up = false
				prevUpper = true
			case unicode.IsUpper(r) && prevUpper:
				b.WriteRune(unicode.ToLower(r))
			default:
				b.WriteRune(r)
				prevUpper = unicode.IsUpper(r)
			}
		default:
		}
	}
	return b.String()
}
