// Code generated by staticodegen; DO NOT EDIT.
// Source of truth: dictionary XML under diam/dict/testdata, filtered by
// the allowlist in cmd/staticodegen/model.go.

package gy

// Enumerated values from the dictionary for allowlisted AVPs.

// CC-Request-Type (416) values.
const (
	CCRequestTypeInitialRequest     int32 = 1
	CCRequestTypeUpdateRequest      int32 = 2
	CCRequestTypeTerminationRequest int32 = 3
)

// CC-Session-Failover (418) values.
const (
	CCSessionFailoverFailoverNotSupported int32 = 0
	CCSessionFailoverFailoverSupported    int32 = 1
)

// Credit-Control-Failure-Handling (427) values.
const (
	CreditControlFailureHandlingTerminate         int32 = 0
	CreditControlFailureHandlingContinue          int32 = 1
	CreditControlFailureHandlingRetryAndTerminate int32 = 2
)

// Subscription-Id-Type (450) values.
const (
	SubscriptionIDTypeEndUserE164   int32 = 0
	SubscriptionIDTypeEndUserImsi   int32 = 1
	SubscriptionIDTypeEndUserSipUri int32 = 2
	SubscriptionIDTypeEndUserNai    int32 = 3
)

// User-Equipment-Info-Type (459) values.
const (
	UserEquipmentInfoTypeImeisv        int32 = 0
	UserEquipmentInfoTypeMac           int32 = 1
	UserEquipmentInfoTypeEui64         int32 = 2
	UserEquipmentInfoTypeModifiedEui64 int32 = 3
)

// Termination-Cause (295) values.
const (
	TerminationCauseDiameterLogout             int32 = 1
	TerminationCauseDiameterServiceNotProvided int32 = 2
	TerminationCauseDiameterBadAnswer          int32 = 3
	TerminationCauseDiameterAdministrative     int32 = 4
	TerminationCauseDiameterLinkBroken         int32 = 5
	TerminationCauseDiameterAuthExpired        int32 = 6
	TerminationCauseDiameterUserMoved          int32 = 7
	TerminationCauseDiameterSessionTimeout     int32 = 8
)

// Tariff-Change-Usage (452) values.
const (
	TariffChangeUsageUnitBeforeTariffChange int32 = 0
	TariffChangeUsageUnitAfterTariffChange  int32 = 1
	TariffChangeUsageUnitIndeterminate      int32 = 2
)

// Final-Unit-Action (449) values.
const (
	FinalUnitActionTerminate      int32 = 0
	FinalUnitActionRedirect       int32 = 1
	FinalUnitActionRestrictAccess int32 = 2
)

// Trigger-Type (870) values.
const (
	TriggerTypeChangeInSgsnIpAddress                        int32 = 1
	TriggerTypeChangeInQos                                  int32 = 2
	TriggerTypeChangeInLocation                             int32 = 3
	TriggerTypeChangeInRat                                  int32 = 4
	TriggerTypeChangeInUeTimezone                           int32 = 5
	TriggerTypeChangeinqosTrafficClass                      int32 = 10
	TriggerTypeChangeinqosReliabilityClass                  int32 = 11
	TriggerTypeChangeinqosPeakThroughput                    int32 = 13
	TriggerTypeChangeinqosPrecedenceClass                   int32 = 14
	TriggerTypeChangeinqosMeanThroughput                    int32 = 15
	TriggerTypeChangeinqosMaximumBitRateForUplink           int32 = 16
	TriggerTypeChangeinqosMaximumBitRateForDownlink         int32 = 17
	TriggerTypeChangeinqosResidualBer                       int32 = 18
	TriggerTypeChangeinqosSduErrorRatio                     int32 = 19
	TriggerTypeChangeinqosTransferDelay                     int32 = 20
	TriggerTypeChangeinqosTrafficHandlingPriority           int32 = 21
	TriggerTypeChangeinqosGuaranteedBitRateForUplink        int32 = 22
	TriggerTypeChangeinqosGuaranteedBitRateForDownlink      int32 = 23
	TriggerTypeChangeinqosApnAggregateMaximumBitRate        int32 = 24
	TriggerTypeChangeinlocationMcc                          int32 = 30
	TriggerTypeChangeinlocationMnc                          int32 = 31
	TriggerTypeChangeinlocationRac                          int32 = 32
	TriggerTypeChangeinlocationLac                          int32 = 33
	TriggerTypeChangeinlocationCellId                       int32 = 34
	TriggerTypeChangeinlocationTac                          int32 = 35
	TriggerTypeChangeinlocationEcgi                         int32 = 36
	TriggerTypeChangeInMediaComposition                     int32 = 40
	TriggerTypeChangeInParticipantsNmb                      int32 = 50
	TriggerTypeChangeInThrshldOfParticipantsNmb             int32 = 51
	TriggerTypeChangeInUserParticipatingType                int32 = 52
	TriggerTypeChangeInServiceCondition                     int32 = 60
	TriggerTypeChangeInServingNode                          int32 = 61
	TriggerTypeChangeInUserCsgInformation                   int32 = 70
	TriggerTypeChangeInHybridSubscribedUserCsgInformation   int32 = 71
	TriggerTypeChangeInHybridUnsubscribedUserCsgInformation int32 = 72
	TriggerTypeChangeOfUePresenceInPresenceReportingArea    int32 = 73
)

// TGPP-PDP-Type (3) values.
const (
	TGPPPDPTypeIpv4   int32 = 0
	TGPPPDPTypePpp    int32 = 1
	TGPPPDPTypeIpv6   int32 = 2
	TGPPPDPTypeIpv4v6 int32 = 3
)
