// Copyright 2013-2026 go-diameter authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package gy

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Golden fixtures generated by bench/fixtures/gen.go with the dictionary
// codec; they double as cross-codec equivalence references.
var fixtureNames = []string{
	"ccr_i_1mscc_rsu",
	"ccr_u_1mscc",
	"ccr_u_3mscc",
	"ccr_u_5mscc",
	"ccr_u_trigger_ttc",
	"ccr_t_final_usu",
	"cca_i_gsu_validity",
	"cca_u_mscc_resultcodes",
	"cca_fui_terminate",
	"ccr_unknown_vendor_avps",
}

func loadFixture(tb testing.TB, name string) []byte {
	tb.Helper()
	b, err := os.ReadFile(filepath.Join("..", "..", "bench", "fixtures", name+".bin"))
	if err != nil {
		tb.Fatalf("fixture %s: %v (run: go run bench/fixtures/gen.go)", name, err)
	}
	return b
}

// isRequest routes a fixture to CCR (true) or CCA (false) by name.
func isRequest(name string) bool {
	return strings.HasPrefix(name, "ccr_")
}

// parseFixture parses a fixture into the matching message type and
// returns it behind the common interface used by the tests.
type gyMessage interface {
	ParseFrom(buf []byte) error
	AppendTo(dst []byte) []byte
}

func newMessageFor(name string) gyMessage {
	if isRequest(name) {
		return new(CCR)
	}
	return new(CCA)
}
