// Code generated by staticodegen; DO NOT EDIT.
// Source of truth: dictionary XML under diam/dict/testdata, filtered by
// the allowlist in cmd/staticodegen/model.go.

package sy

// Enumerated values from the dictionary for allowlisted AVPs.

// SL-Request-Type (2904) values.
const (
	SLRequestTypeInitialRequest      int32 = 0
	SLRequestTypeIntermediateRequest int32 = 1
)

// Subscription-Id-Type (450) values.
const (
	SubscriptionIDTypeEndUserE164   int32 = 0
	SubscriptionIDTypeEndUserImsi   int32 = 1
	SubscriptionIDTypeEndUserSipUri int32 = 2
	SubscriptionIDTypeEndUserNai    int32 = 3
)
