// Code generated by staticodegen; DO NOT EDIT.
// Source of truth: dictionary XML under diam/dict/testdata, filtered by
// the allowlist in cmd/staticodegen/model.go.

package sy

import "github.com/fiorix/go-diameter/v4/staticodec"

// SubscriptionID is the Subscription-Id grouped AVP (RFC 4006, reused by Sy).
//
// OWNERSHIP: all []byte fields (including staticodec.RawAVP data) alias the
// read buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type SubscriptionID struct {
	Type    int32 // Subscription-Id-Type (450)
	HasType bool
	Data    []byte // Subscription-Id-Data (444)

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []staticodec.RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []staticodec.RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *SubscriptionID) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := staticodec.WalkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 450 && vendorID == 0: // Subscription-Id-Type (450)
			if len(data) != 4 {
				return staticodec.ErrBadAVPData
			}
			v.Type = int32(staticodec.BE32(data))
			v.HasType = true
		case code == 444 && vendorID == 0: // Subscription-Id-Data (444)
			v.Data = data
		default:
			raw := staticodec.RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&staticodec.FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *SubscriptionID) appendGroup(dst []byte) []byte {
	if v.HasType { // Subscription-Id-Type (450)
		dst = staticodec.AppendAVPInt32(dst, 450, 0x40, 0, v.Type)
	}
	if v.Data != nil { // Subscription-Id-Data (444)
		dst = staticodec.AppendAVPBytes(dst, 444, 0x40, 0, v.Data)
	}
	for i := range v.Other {
		dst = v.Other[i].AppendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools SubscriptionID values).
func (v *SubscriptionID) Reset() {
	v.Type = 0
	v.HasType = false
	v.Data = nil
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *SubscriptionID) Clone() *SubscriptionID {
	c := *v
	c.Data = append([]byte(nil), v.Data...)
	c.UnsupportedMandatory = staticodec.CloneRawAVPs(v.UnsupportedMandatory)
	c.Other = staticodec.CloneRawAVPs(v.Other)
	return &c
}

// PendingPolicyCounterInformation is the Pending-Policy-Counter-Information grouped AVP (TS 29.219 §5.3.5).
//
// OWNERSHIP: all []byte fields (including staticodec.RawAVP data) alias the
// read buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type PendingPolicyCounterInformation struct {
	PolicyCounterStatus               []byte // Policy-Counter-Status (2902, vendor 10415)
	PendingPolicyCounterChangeTime    uint32 // Pending-Policy-Counter-Change-Time (2906, vendor 10415)
	HasPendingPolicyCounterChangeTime bool

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []staticodec.RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []staticodec.RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *PendingPolicyCounterInformation) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := staticodec.WalkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 2902 && vendorID == 10415: // Policy-Counter-Status (2902, vendor 10415)
			v.PolicyCounterStatus = data
		case code == 2906 && vendorID == 10415: // Pending-Policy-Counter-Change-Time (2906, vendor 10415)
			if len(data) != 4 {
				return staticodec.ErrBadAVPData
			}
			v.PendingPolicyCounterChangeTime = staticodec.BE32(data)
			v.HasPendingPolicyCounterChangeTime = true
		default:
			raw := staticodec.RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&staticodec.FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *PendingPolicyCounterInformation) appendGroup(dst []byte) []byte {
	if v.PolicyCounterStatus != nil { // Policy-Counter-Status (2902, vendor 10415)
		dst = staticodec.AppendAVPBytes(dst, 2902, 0xc0, 10415, v.PolicyCounterStatus)
	}
	if v.HasPendingPolicyCounterChangeTime { // Pending-Policy-Counter-Change-Time (2906, vendor 10415)
		dst = staticodec.AppendAVPUint32(dst, 2906, 0xc0, 10415, v.PendingPolicyCounterChangeTime)
	}
	for i := range v.Other {
		dst = v.Other[i].AppendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools PendingPolicyCounterInformation values).
func (v *PendingPolicyCounterInformation) Reset() {
	v.PolicyCounterStatus = nil
	v.PendingPolicyCounterChangeTime = 0
	v.HasPendingPolicyCounterChangeTime = false
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *PendingPolicyCounterInformation) Clone() *PendingPolicyCounterInformation {
	c := *v
	c.PolicyCounterStatus = append([]byte(nil), v.PolicyCounterStatus...)
	c.UnsupportedMandatory = staticodec.CloneRawAVPs(v.UnsupportedMandatory)
	c.Other = staticodec.CloneRawAVPs(v.Other)
	return &c
}

// PolicyCounterStatusReport is the Policy-Counter-Status-Report grouped AVP (TS 29.219 §5.3.3).
//
// OWNERSHIP: all []byte fields (including staticodec.RawAVP data) alias the
// read buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type PolicyCounterStatusReport struct {
	PolicyCounterIdentifier         []byte                            // Policy-Counter-Identifier (2901, vendor 10415)
	PolicyCounterStatus             []byte                            // Policy-Counter-Status (2902, vendor 10415)
	PendingPolicyCounterInformation []PendingPolicyCounterInformation // Pending-Policy-Counter-Information (2905, vendor 10415)

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []staticodec.RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []staticodec.RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *PolicyCounterStatusReport) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := staticodec.WalkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 2901 && vendorID == 10415: // Policy-Counter-Identifier (2901, vendor 10415)
			v.PolicyCounterIdentifier = data
		case code == 2902 && vendorID == 10415: // Policy-Counter-Status (2902, vendor 10415)
			v.PolicyCounterStatus = data
		case code == 2905 && vendorID == 10415: // Pending-Policy-Counter-Information (2905, vendor 10415)
			if cap(v.PendingPolicyCounterInformation) > len(v.PendingPolicyCounterInformation) {
				v.PendingPolicyCounterInformation = v.PendingPolicyCounterInformation[:len(v.PendingPolicyCounterInformation)+1]
				v.PendingPolicyCounterInformation[len(v.PendingPolicyCounterInformation)-1].Reset()
			} else {
				v.PendingPolicyCounterInformation = append(v.PendingPolicyCounterInformation, PendingPolicyCounterInformation{})
			}
			if err := v.PendingPolicyCounterInformation[len(v.PendingPolicyCounterInformation)-1].parseGroup(data); err != nil {
				return err
			}
		default:
			raw := staticodec.RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&staticodec.FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *PolicyCounterStatusReport) appendGroup(dst []byte) []byte {
	var gOff int
	if v.PolicyCounterIdentifier != nil { // Policy-Counter-Identifier (2901, vendor 10415)
		dst = staticodec.AppendAVPBytes(dst, 2901, 0xc0, 10415, v.PolicyCounterIdentifier)
	}
	if v.PolicyCounterStatus != nil { // Policy-Counter-Status (2902, vendor 10415)
		dst = staticodec.AppendAVPBytes(dst, 2902, 0xc0, 10415, v.PolicyCounterStatus)
	}
	for i := range v.PendingPolicyCounterInformation { // Pending-Policy-Counter-Information (2905, vendor 10415)
		dst, gOff = staticodec.OpenGroupedAVP(dst, 2905, 0xc0, 10415)
		dst = v.PendingPolicyCounterInformation[i].appendGroup(dst)
		dst = staticodec.CloseGroupedAVP(dst, gOff)
	}
	for i := range v.Other {
		dst = v.Other[i].AppendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools PolicyCounterStatusReport values).
func (v *PolicyCounterStatusReport) Reset() {
	v.PolicyCounterIdentifier = nil
	v.PolicyCounterStatus = nil
	v.PendingPolicyCounterInformation = v.PendingPolicyCounterInformation[:0]
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *PolicyCounterStatusReport) Clone() *PolicyCounterStatusReport {
	c := *v
	c.PolicyCounterIdentifier = append([]byte(nil), v.PolicyCounterIdentifier...)
	c.PolicyCounterStatus = append([]byte(nil), v.PolicyCounterStatus...)
	if v.PendingPolicyCounterInformation != nil {
		c.PendingPolicyCounterInformation = make([]PendingPolicyCounterInformation, len(v.PendingPolicyCounterInformation))
		for i := range v.PendingPolicyCounterInformation {
			c.PendingPolicyCounterInformation[i] = *v.PendingPolicyCounterInformation[i].Clone()
		}
	}
	c.UnsupportedMandatory = staticodec.CloneRawAVPs(v.UnsupportedMandatory)
	c.Other = staticodec.CloneRawAVPs(v.Other)
	return &c
}
