// Code generated by staticodegen; DO NOT EDIT.
// Source of truth: dictionary XML under diam/dict/testdata, filtered by
// the allowlist in cmd/staticodegen/model.go.

package sy

import "github.com/fiorix/go-diameter/v4/staticodec"

// SLA is a Sy Spending-Limit-Answer (Application-Id 16777302, command 8388635).
//
// OWNERSHIP: all []byte fields (including staticodec.RawAVP data) alias the
// read buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type SLA struct {
	// Hdr is the fixed Diameter header. ParseFrom fills it; for
	// hand-built messages set CommandFlags/HopByHopID/EndToEndID
	// before AppendTo (command code and app id are set by AppendTo).
	Hdr staticodec.Header

	SessionID                 []byte // Session-Id (263)
	AuthApplicationID         uint32 // Auth-Application-Id (258)
	HasAuthApplicationID      bool
	OriginHost                []byte // Origin-Host (264)
	OriginRealm               []byte // Origin-Realm (296)
	ResultCode                uint32 // Result-Code (268)
	HasResultCode             bool
	PolicyCounterStatusReport []PolicyCounterStatusReport // Policy-Counter-Status-Report (2903, vendor 10415)
	OriginStateID             uint32                      // Origin-State-Id (278)
	HasOriginStateID          bool

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []staticodec.RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []staticodec.RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *SLA) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := staticodec.WalkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 263 && vendorID == 0: // Session-Id (263)
			v.SessionID = data
		case code == 258 && vendorID == 0: // Auth-Application-Id (258)
			if len(data) != 4 {
				return staticodec.ErrBadAVPData
			}
			v.AuthApplicationID = staticodec.BE32(data)
			v.HasAuthApplicationID = true
		case code == 264 && vendorID == 0: // Origin-Host (264)
			v.OriginHost = data
		case code == 296 && vendorID == 0: // Origin-Realm (296)
			v.OriginRealm = data
		case code == 268 && vendorID == 0: // Result-Code (268)
			if len(data) != 4 {
				return staticodec.ErrBadAVPData
			}
			v.ResultCode = staticodec.BE32(data)
			v.HasResultCode = true
		case code == 2903 && vendorID == 10415: // Policy-Counter-Status-Report (2903, vendor 10415)
			if cap(v.PolicyCounterStatusReport) > len(v.PolicyCounterStatusReport) {
				v.PolicyCounterStatusReport = v.PolicyCounterStatusReport[:len(v.PolicyCounterStatusReport)+1]
				v.PolicyCounterStatusReport[len(v.PolicyCounterStatusReport)-1].Reset()
			} else {
				v.PolicyCounterStatusReport = append(v.PolicyCounterStatusReport, PolicyCounterStatusReport{})
			}
			if err := v.PolicyCounterStatusReport[len(v.PolicyCounterStatusReport)-1].parseGroup(data); err != nil {
				return err
			}
		case code == 278 && vendorID == 0: // Origin-State-Id (278)
			if len(data) != 4 {
				return staticodec.ErrBadAVPData
			}
			v.OriginStateID = staticodec.BE32(data)
			v.HasOriginStateID = true
		default:
			raw := staticodec.RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&staticodec.FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *SLA) appendGroup(dst []byte) []byte {
	var gOff int
	if v.SessionID != nil { // Session-Id (263)
		dst = staticodec.AppendAVPBytes(dst, 263, 0x40, 0, v.SessionID)
	}
	if v.HasAuthApplicationID { // Auth-Application-Id (258)
		dst = staticodec.AppendAVPUint32(dst, 258, 0x40, 0, v.AuthApplicationID)
	}
	if v.OriginHost != nil { // Origin-Host (264)
		dst = staticodec.AppendAVPBytes(dst, 264, 0x40, 0, v.OriginHost)
	}
	if v.OriginRealm != nil { // Origin-Realm (296)
		dst = staticodec.AppendAVPBytes(dst, 296, 0x40, 0, v.OriginRealm)
	}
	if v.HasResultCode { // Result-Code (268)
		dst = staticodec.AppendAVPUint32(dst, 268, 0x40, 0, v.ResultCode)
	}
	for i := range v.PolicyCounterStatusReport { // Policy-Counter-Status-Report (2903, vendor 10415)
		dst, gOff = staticodec.OpenGroupedAVP(dst, 2903, 0xc0, 10415)
		dst = v.PolicyCounterStatusReport[i].appendGroup(dst)
		dst = staticodec.CloseGroupedAVP(dst, gOff)
	}
	if v.HasOriginStateID { // Origin-State-Id (278)
		dst = staticodec.AppendAVPUint32(dst, 278, 0x40, 0, v.OriginStateID)
	}
	for i := range v.Other {
		dst = v.Other[i].AppendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools SLA values).
func (v *SLA) Reset() {
	v.Hdr = staticodec.Header{}
	v.SessionID = nil
	v.AuthApplicationID = 0
	v.HasAuthApplicationID = false
	v.OriginHost = nil
	v.OriginRealm = nil
	v.ResultCode = 0
	v.HasResultCode = false
	v.PolicyCounterStatusReport = v.PolicyCounterStatusReport[:0]
	v.OriginStateID = 0
	v.HasOriginStateID = false
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *SLA) Clone() *SLA {
	c := *v
	c.SessionID = append([]byte(nil), v.SessionID...)
	c.OriginHost = append([]byte(nil), v.OriginHost...)
	c.OriginRealm = append([]byte(nil), v.OriginRealm...)
	if v.PolicyCounterStatusReport != nil {
		c.PolicyCounterStatusReport = make([]PolicyCounterStatusReport, len(v.PolicyCounterStatusReport))
		for i := range v.PolicyCounterStatusReport {
			c.PolicyCounterStatusReport[i] = *v.PolicyCounterStatusReport[i].Clone()
		}
	}
	c.UnsupportedMandatory = staticodec.CloneRawAVPs(v.UnsupportedMandatory)
	c.Other = staticodec.CloneRawAVPs(v.Other)
	return &c
}

// ParseFrom decodes a complete Diameter message (including the
// 20-byte header) into m. It never panics on malformed input.
func (m *SLA) ParseFrom(buf []byte) error {
	m.Reset()
	h, err := staticodec.ParseHeader(buf)
	if err != nil {
		return err
	}
	if h.CommandCode != 8388635 {
		return staticodec.ErrUnexpectedCommand
	}
	m.Hdr = h
	return m.parseGroup(buf[staticodec.HeaderLength:])
}

// AppendTo serializes m append-style (like strconv.Append*) so the
// caller controls buffer reuse. Command code and application id are
// fixed (8388635/16777302); flags and hop/end ids come from m.Hdr. Message and
// grouped lengths are reserve-and-backpatched in a single pass.
func (m *SLA) AppendTo(dst []byte) []byte {
	msgOff := len(dst)
	h := m.Hdr
	h.CommandCode = 8388635
	h.ApplicationID = 16777302
	dst = staticodec.AppendHeader(dst, h)
	dst = m.appendGroup(dst)
	staticodec.BackpatchMessageLength(dst, msgOff)
	return dst
}
