// Code generated by staticodegen; DO NOT EDIT.
// Source of truth: dictionary XML under diam/dict/testdata, filtered by
// the allowlist in cmd/staticodegen/model.go.

package sy

import "github.com/fiorix/go-diameter/v4/staticodec"

// SLR is a Sy Spending-Limit-Request (Application-Id 16777302, command 8388635).
//
// OWNERSHIP: all []byte fields (including staticodec.RawAVP data) alias the
// read buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type SLR struct {
	// Hdr is the fixed Diameter header. ParseFrom fills it; for
	// hand-built messages set CommandFlags/HopByHopID/EndToEndID
	// before AppendTo (command code and app id are set by AppendTo).
	Hdr staticodec.Header

	SessionID               []byte // Session-Id (263)
	AuthApplicationID       uint32 // Auth-Application-Id (258)
	HasAuthApplicationID    bool
	OriginHost              []byte // Origin-Host (264)
	OriginRealm             []byte // Origin-Realm (296)
	DestinationRealm        []byte // Destination-Realm (283)
	DestinationHost         []byte // Destination-Host (293)
	OriginStateID           uint32 // Origin-State-Id (278)
	HasOriginStateID        bool
	SLRequestType           int32 // SL-Request-Type (2904, vendor 10415)
	HasSLRequestType        bool
	SubscriptionID          []SubscriptionID // Subscription-Id (443)
	PolicyCounterIdentifier [][]byte         // Policy-Counter-Identifier (2901, vendor 10415)

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []staticodec.RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []staticodec.RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *SLR) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := staticodec.WalkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 263 && vendorID == 0: // Session-Id (263)
			v.SessionID = data
		case code == 258 && vendorID == 0: // Auth-Application-Id (258)
			if len(data) != 4 {
				return staticodec.ErrBadAVPData
			}
			v.AuthApplicationID = staticodec.BE32(data)
			v.HasAuthApplicationID = true
		case code == 264 && vendorID == 0: // Origin-Host (264)
			v.OriginHost = data
		case code == 296 && vendorID == 0: // Origin-Realm (296)
			v.OriginRealm = data
		case code == 283 && vendorID == 0: // Destination-Realm (283)
			v.DestinationRealm = data
		case code == 293 && vendorID == 0: // Destination-Host (293)
			v.DestinationHost = data
		case code == 278 && vendorID == 0: // Origin-State-Id (278)
			if len(data) != 4 {
				return staticodec.ErrBadAVPData
			}
			v.OriginStateID = staticodec.BE32(data)
			v.HasOriginStateID = true
		case code == 2904 && vendorID == 10415: // SL-Request-Type (2904, vendor 10415)
			if len(data) != 4 {
				return staticodec.ErrBadAVPData
			}
			v.SLRequestType = int32(staticodec.BE32(data))
			v.HasSLRequestType = true
		case code == 443 && vendorID == 0: // Subscription-Id (443)
			if cap(v.SubscriptionID) > len(v.SubscriptionID) {
				v.SubscriptionID = v.SubscriptionID[:len(v.SubscriptionID)+1]
				v.SubscriptionID[len(v.SubscriptionID)-1].Reset()
			} else {
				v.SubscriptionID = append(v.SubscriptionID, SubscriptionID{})
			}
			if err := v.SubscriptionID[len(v.SubscriptionID)-1].parseGroup(data); err != nil {
				return err
			}
		case code == 2901 && vendorID == 10415: // Policy-Counter-Identifier (2901, vendor 10415)
			v.PolicyCounterIdentifier = append(v.PolicyCounterIdentifier, data)
		default:
			raw := staticodec.RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&staticodec.FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *SLR) appendGroup(dst []byte) []byte {
	var gOff int
	if v.SessionID != nil { // Session-Id (263)
		dst = staticodec.AppendAVPBytes(dst, 263, 0x40, 0, v.SessionID)
	}
	if v.HasAuthApplicationID { // Auth-Application-Id (258)
		dst = staticodec.AppendAVPUint32(dst, 258, 0x40, 0, v.AuthApplicationID)
	}
	if v.OriginHost != nil { // Origin-Host (264)
		dst = staticodec.AppendAVPBytes(dst, 264, 0x40, 0, v.OriginHost)
	}
	if v.OriginRealm != nil { // Origin-Realm (296)
		dst = staticodec.AppendAVPBytes(dst, 296, 0x40, 0, v.OriginRealm)
	}
	if v.DestinationRealm != nil { // Destination-Realm (283)
		dst = staticodec.AppendAVPBytes(dst, 283, 0x40, 0, v.DestinationRealm)
	}
	if v.DestinationHost != nil { // Destination-Host (293)
		dst = staticodec.AppendAVPBytes(dst, 293, 0x40, 0, v.DestinationHost)
	}
	if v.HasOriginStateID { // Origin-State-Id (278)
		dst = staticodec.AppendAVPUint32(dst, 278, 0x40, 0, v.OriginStateID)
	}
	if v.HasSLRequestType { // SL-Request-Type (2904, vendor 10415)
		dst = staticodec.AppendAVPInt32(dst, 2904, 0xc0, 10415, v.SLRequestType)
	}
	for i := range v.SubscriptionID { // Subscription-Id (443)
		dst, gOff = staticodec.OpenGroupedAVP(dst, 443, 0x40, 0)
		dst = v.SubscriptionID[i].appendGroup(dst)
		dst = staticodec.CloseGroupedAVP(dst, gOff)
	}
	for _, b := range v.PolicyCounterIdentifier { // Policy-Counter-Identifier (2901, vendor 10415)
		dst = staticodec.AppendAVPBytes(dst, 2901, 0xc0, 10415, b)
	}
	for i := range v.Other {
		dst = v.Other[i].AppendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools SLR values).
func (v *SLR) Reset() {
	v.Hdr = staticodec.Header{}
	v.SessionID = nil
	v.AuthApplicationID = 0
	v.HasAuthApplicationID = false
	v.OriginHost = nil
	v.OriginRealm = nil
	v.DestinationRealm = nil
	v.DestinationHost = nil
	v.OriginStateID = 0
	v.HasOriginStateID = false
	v.SLRequestType = 0
	v.HasSLRequestType = false
	v.SubscriptionID = v.SubscriptionID[:0]
	v.PolicyCounterIdentifier = v.PolicyCounterIdentifier[:0]
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *SLR) Clone() *SLR {
	c := *v
	c.SessionID = append([]byte(nil), v.SessionID...)
	c.OriginHost = append([]byte(nil), v.OriginHost...)
	c.OriginRealm = append([]byte(nil), v.OriginRealm...)
	c.DestinationRealm = append([]byte(nil), v.DestinationRealm...)
	c.DestinationHost = append([]byte(nil), v.DestinationHost...)
	if v.SubscriptionID != nil {
		c.SubscriptionID = make([]SubscriptionID, len(v.SubscriptionID))
		for i := range v.SubscriptionID {
			c.SubscriptionID[i] = *v.SubscriptionID[i].Clone()
		}
	}
	if v.PolicyCounterIdentifier != nil {
		c.PolicyCounterIdentifier = make([][]byte, len(v.PolicyCounterIdentifier))
		for i := range v.PolicyCounterIdentifier {
			c.PolicyCounterIdentifier[i] = append([]byte(nil), v.PolicyCounterIdentifier[i]...)
		}
	}
	c.UnsupportedMandatory = staticodec.CloneRawAVPs(v.UnsupportedMandatory)
	c.Other = staticodec.CloneRawAVPs(v.Other)
	return &c
}

// ParseFrom decodes a complete Diameter message (including the
// 20-byte header) into m. It never panics on malformed input.
func (m *SLR) ParseFrom(buf []byte) error {
	m.Reset()
	h, err := staticodec.ParseHeader(buf)
	if err != nil {
		return err
	}
	if h.CommandCode != 8388635 {
		return staticodec.ErrUnexpectedCommand
	}
	m.Hdr = h
	return m.parseGroup(buf[staticodec.HeaderLength:])
}

// AppendTo serializes m append-style (like strconv.Append*) so the
// caller controls buffer reuse. Command code and application id are
// fixed (8388635/16777302); flags and hop/end ids come from m.Hdr. Message and
// grouped lengths are reserve-and-backpatched in a single pass.
func (m *SLR) AppendTo(dst []byte) []byte {
	msgOff := len(dst)
	h := m.Hdr
	h.CommandCode = 8388635
	h.ApplicationID = 16777302
	dst = staticodec.AppendHeader(dst, h)
	dst = m.appendGroup(dst)
	staticodec.BackpatchMessageLength(dst, msgOff)
	return dst
}
