// Code generated by gycodegen; DO NOT EDIT.
// Source of truth: dictionary XML under diam/dict/testdata, filtered by
// the allowlist in cmd/gycodegen/model.go.

package gycodec

// CCA is a Gy Credit-Control-Answer (Application-Id 4, command 272).
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type CCA struct {
	// Hdr is the fixed Diameter header. ParseFrom fills it; for
	// hand-built messages set CommandFlags/HopByHopID/EndToEndID
	// before AppendTo (command code and app id are set by AppendTo).
	Hdr Header

	SessionID                       []byte // Session-Id (263)
	ResultCode                      uint32 // Result-Code (268)
	HasResultCode                   bool
	OriginHost                      []byte // Origin-Host (264)
	OriginRealm                     []byte // Origin-Realm (296)
	AuthApplicationID               uint32 // Auth-Application-Id (258)
	HasAuthApplicationID            bool
	CCRequestType                   int32 // CC-Request-Type (416)
	HasCCRequestType                bool
	CCRequestNumber                 uint32 // CC-Request-Number (415)
	HasCCRequestNumber              bool
	MSCC                            []MSCC // Multiple-Services-Credit-Control (456)
	CCSessionFailover               int32  // CC-Session-Failover (418)
	HasCCSessionFailover            bool
	CreditControlFailureHandling    int32 // Credit-Control-Failure-Handling (427)
	HasCreditControlFailureHandling bool

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *CCA) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 263 && vendorID == 0: // Session-Id (263)
			v.SessionID = data
		case code == 268 && vendorID == 0: // Result-Code (268)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.ResultCode = be32(data)
			v.HasResultCode = true
		case code == 264 && vendorID == 0: // Origin-Host (264)
			v.OriginHost = data
		case code == 296 && vendorID == 0: // Origin-Realm (296)
			v.OriginRealm = data
		case code == 258 && vendorID == 0: // Auth-Application-Id (258)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.AuthApplicationID = be32(data)
			v.HasAuthApplicationID = true
		case code == 416 && vendorID == 0: // CC-Request-Type (416)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.CCRequestType = int32(be32(data))
			v.HasCCRequestType = true
		case code == 415 && vendorID == 0: // CC-Request-Number (415)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.CCRequestNumber = be32(data)
			v.HasCCRequestNumber = true
		case code == 456 && vendorID == 0: // Multiple-Services-Credit-Control (456)
			if cap(v.MSCC) > len(v.MSCC) {
				v.MSCC = v.MSCC[:len(v.MSCC)+1]
				v.MSCC[len(v.MSCC)-1].Reset()
			} else {
				v.MSCC = append(v.MSCC, MSCC{})
			}
			if err := v.MSCC[len(v.MSCC)-1].parseGroup(data); err != nil {
				return err
			}
		case code == 418 && vendorID == 0: // CC-Session-Failover (418)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.CCSessionFailover = int32(be32(data))
			v.HasCCSessionFailover = true
		case code == 427 && vendorID == 0: // Credit-Control-Failure-Handling (427)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.CreditControlFailureHandling = int32(be32(data))
			v.HasCreditControlFailureHandling = true
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *CCA) appendGroup(dst []byte) []byte {
	var gOff int
	if v.SessionID != nil { // Session-Id (263)
		dst = appendAVPBytes(dst, 263, 0x40, 0, v.SessionID)
	}
	if v.HasResultCode { // Result-Code (268)
		dst = appendAVPUint32(dst, 268, 0x40, 0, v.ResultCode)
	}
	if v.OriginHost != nil { // Origin-Host (264)
		dst = appendAVPBytes(dst, 264, 0x40, 0, v.OriginHost)
	}
	if v.OriginRealm != nil { // Origin-Realm (296)
		dst = appendAVPBytes(dst, 296, 0x40, 0, v.OriginRealm)
	}
	if v.HasAuthApplicationID { // Auth-Application-Id (258)
		dst = appendAVPUint32(dst, 258, 0x40, 0, v.AuthApplicationID)
	}
	if v.HasCCRequestType { // CC-Request-Type (416)
		dst = appendAVPInt32(dst, 416, 0x40, 0, v.CCRequestType)
	}
	if v.HasCCRequestNumber { // CC-Request-Number (415)
		dst = appendAVPUint32(dst, 415, 0x40, 0, v.CCRequestNumber)
	}
	for i := range v.MSCC { // Multiple-Services-Credit-Control (456)
		dst, gOff = openGroupedAVP(dst, 456, 0x40, 0)
		dst = v.MSCC[i].appendGroup(dst)
		dst = closeGroupedAVP(dst, gOff)
	}
	if v.HasCCSessionFailover { // CC-Session-Failover (418)
		dst = appendAVPInt32(dst, 418, 0x40, 0, v.CCSessionFailover)
	}
	if v.HasCreditControlFailureHandling { // Credit-Control-Failure-Handling (427)
		dst = appendAVPInt32(dst, 427, 0x40, 0, v.CreditControlFailureHandling)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools CCA values).
func (v *CCA) Reset() {
	v.Hdr = Header{}
	v.SessionID = nil
	v.ResultCode = 0
	v.HasResultCode = false
	v.OriginHost = nil
	v.OriginRealm = nil
	v.AuthApplicationID = 0
	v.HasAuthApplicationID = false
	v.CCRequestType = 0
	v.HasCCRequestType = false
	v.CCRequestNumber = 0
	v.HasCCRequestNumber = false
	v.MSCC = v.MSCC[:0]
	v.CCSessionFailover = 0
	v.HasCCSessionFailover = false
	v.CreditControlFailureHandling = 0
	v.HasCreditControlFailureHandling = false
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *CCA) Clone() *CCA {
	c := *v
	c.SessionID = append([]byte(nil), v.SessionID...)
	c.OriginHost = append([]byte(nil), v.OriginHost...)
	c.OriginRealm = append([]byte(nil), v.OriginRealm...)
	if v.MSCC != nil {
		c.MSCC = make([]MSCC, len(v.MSCC))
		for i := range v.MSCC {
			c.MSCC[i] = *v.MSCC[i].Clone()
		}
	}
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}

// ParseFrom decodes a complete Diameter message (including the
// 20-byte header) into m. It never panics on malformed input.
func (m *CCA) ParseFrom(buf []byte) error {
	m.Reset()
	h, err := ParseHeader(buf)
	if err != nil {
		return err
	}
	if h.CommandCode != 272 {
		return ErrUnexpectedCommand
	}
	m.Hdr = h
	return m.parseGroup(buf[HeaderLength:])
}

// AppendTo serializes m append-style (like strconv.Append*) so the
// caller controls buffer reuse. Command code and application id are
// fixed (272/4); flags and hop/end ids come from m.Hdr. Message and
// grouped lengths are reserve-and-backpatched in a single pass.
func (m *CCA) AppendTo(dst []byte) []byte {
	msgOff := len(dst)
	h := m.Hdr
	h.CommandCode = 272
	h.ApplicationID = 4
	dst = appendHeader(dst, h)
	dst = m.appendGroup(dst)
	backpatchMessageLength(dst, msgOff)
	return dst
}
