// Code generated by gycodegen; DO NOT EDIT.
// Source of truth: dictionary XML under diam/dict/testdata, filtered by
// the allowlist in cmd/gycodegen/model.go.

package gycodec

// CCR is a Gy Credit-Control-Request (Application-Id 4, command 272).
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type CCR struct {
	// Hdr is the fixed Diameter header. ParseFrom fills it; for
	// hand-built messages set CommandFlags/HopByHopID/EndToEndID
	// before AppendTo (command code and app id are set by AppendTo).
	Hdr Header

	SessionID             []byte // Session-Id (263)
	OriginHost            []byte // Origin-Host (264)
	OriginRealm           []byte // Origin-Realm (296)
	DestinationRealm      []byte // Destination-Realm (283)
	AuthApplicationID     uint32 // Auth-Application-Id (258)
	HasAuthApplicationID  bool
	ServiceContextID      []byte // Service-Context-Id (461)
	CCRequestType         int32  // CC-Request-Type (416)
	HasCCRequestType      bool
	CCRequestNumber       uint32 // CC-Request-Number (415)
	HasCCRequestNumber    bool
	DestinationHost       []byte            // Destination-Host (293)
	SubscriptionID        []SubscriptionID  // Subscription-Id (443)
	UserEquipmentInfo     UserEquipmentInfo // User-Equipment-Info (458)
	HasUserEquipmentInfo  bool
	TerminationCause      int32 // Termination-Cause (295)
	HasTerminationCause   bool
	OriginStateID         uint32 // Origin-State-Id (278)
	HasOriginStateID      bool
	EventTimestamp        uint32 // Event-Timestamp (55)
	HasEventTimestamp     bool
	MSCC                  []MSCC             // Multiple-Services-Credit-Control (456)
	ServiceInformation    ServiceInformation // Service-Information (873, vendor 10415)
	HasServiceInformation bool

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *CCR) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 263 && vendorID == 0: // Session-Id (263)
			v.SessionID = data
		case code == 264 && vendorID == 0: // Origin-Host (264)
			v.OriginHost = data
		case code == 296 && vendorID == 0: // Origin-Realm (296)
			v.OriginRealm = data
		case code == 283 && vendorID == 0: // Destination-Realm (283)
			v.DestinationRealm = data
		case code == 258 && vendorID == 0: // Auth-Application-Id (258)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.AuthApplicationID = be32(data)
			v.HasAuthApplicationID = true
		case code == 461 && vendorID == 0: // Service-Context-Id (461)
			v.ServiceContextID = data
		case code == 416 && vendorID == 0: // CC-Request-Type (416)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.CCRequestType = int32(be32(data))
			v.HasCCRequestType = true
		case code == 415 && vendorID == 0: // CC-Request-Number (415)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.CCRequestNumber = be32(data)
			v.HasCCRequestNumber = true
		case code == 293 && vendorID == 0: // Destination-Host (293)
			v.DestinationHost = data
		case code == 443 && vendorID == 0: // Subscription-Id (443)
			if cap(v.SubscriptionID) > len(v.SubscriptionID) {
				v.SubscriptionID = v.SubscriptionID[:len(v.SubscriptionID)+1]
				v.SubscriptionID[len(v.SubscriptionID)-1].Reset()
			} else {
				v.SubscriptionID = append(v.SubscriptionID, SubscriptionID{})
			}
			if err := v.SubscriptionID[len(v.SubscriptionID)-1].parseGroup(data); err != nil {
				return err
			}
		case code == 458 && vendorID == 0: // User-Equipment-Info (458)
			v.UserEquipmentInfo.Reset()
			if err := v.UserEquipmentInfo.parseGroup(data); err != nil {
				return err
			}
			v.HasUserEquipmentInfo = true
		case code == 295 && vendorID == 0: // Termination-Cause (295)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.TerminationCause = int32(be32(data))
			v.HasTerminationCause = true
		case code == 278 && vendorID == 0: // Origin-State-Id (278)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.OriginStateID = be32(data)
			v.HasOriginStateID = true
		case code == 55 && vendorID == 0: // Event-Timestamp (55)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.EventTimestamp = be32(data)
			v.HasEventTimestamp = true
		case code == 456 && vendorID == 0: // Multiple-Services-Credit-Control (456)
			if cap(v.MSCC) > len(v.MSCC) {
				v.MSCC = v.MSCC[:len(v.MSCC)+1]
				v.MSCC[len(v.MSCC)-1].Reset()
			} else {
				v.MSCC = append(v.MSCC, MSCC{})
			}
			if err := v.MSCC[len(v.MSCC)-1].parseGroup(data); err != nil {
				return err
			}
		case code == 873 && vendorID == 10415: // Service-Information (873, vendor 10415)
			v.ServiceInformation.Reset()
			if err := v.ServiceInformation.parseGroup(data); err != nil {
				return err
			}
			v.HasServiceInformation = true
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *CCR) appendGroup(dst []byte) []byte {
	var gOff int
	if v.SessionID != nil { // Session-Id (263)
		dst = appendAVPBytes(dst, 263, 0x40, 0, v.SessionID)
	}
	if v.OriginHost != nil { // Origin-Host (264)
		dst = appendAVPBytes(dst, 264, 0x40, 0, v.OriginHost)
	}
	if v.OriginRealm != nil { // Origin-Realm (296)
		dst = appendAVPBytes(dst, 296, 0x40, 0, v.OriginRealm)
	}
	if v.DestinationRealm != nil { // Destination-Realm (283)
		dst = appendAVPBytes(dst, 283, 0x40, 0, v.DestinationRealm)
	}
	if v.HasAuthApplicationID { // Auth-Application-Id (258)
		dst = appendAVPUint32(dst, 258, 0x40, 0, v.AuthApplicationID)
	}
	if v.ServiceContextID != nil { // Service-Context-Id (461)
		dst = appendAVPBytes(dst, 461, 0x40, 0, v.ServiceContextID)
	}
	if v.HasCCRequestType { // CC-Request-Type (416)
		dst = appendAVPInt32(dst, 416, 0x40, 0, v.CCRequestType)
	}
	if v.HasCCRequestNumber { // CC-Request-Number (415)
		dst = appendAVPUint32(dst, 415, 0x40, 0, v.CCRequestNumber)
	}
	if v.DestinationHost != nil { // Destination-Host (293)
		dst = appendAVPBytes(dst, 293, 0x40, 0, v.DestinationHost)
	}
	for i := range v.SubscriptionID { // Subscription-Id (443)
		dst, gOff = openGroupedAVP(dst, 443, 0x40, 0)
		dst = v.SubscriptionID[i].appendGroup(dst)
		dst = closeGroupedAVP(dst, gOff)
	}
	if v.HasUserEquipmentInfo { // User-Equipment-Info (458)
		dst, gOff = openGroupedAVP(dst, 458, 0x00, 0)
		dst = v.UserEquipmentInfo.appendGroup(dst)
		dst = closeGroupedAVP(dst, gOff)
	}
	if v.HasTerminationCause { // Termination-Cause (295)
		dst = appendAVPInt32(dst, 295, 0x40, 0, v.TerminationCause)
	}
	if v.HasOriginStateID { // Origin-State-Id (278)
		dst = appendAVPUint32(dst, 278, 0x40, 0, v.OriginStateID)
	}
	if v.HasEventTimestamp { // Event-Timestamp (55)
		dst = appendAVPUint32(dst, 55, 0x40, 0, v.EventTimestamp)
	}
	for i := range v.MSCC { // Multiple-Services-Credit-Control (456)
		dst, gOff = openGroupedAVP(dst, 456, 0x40, 0)
		dst = v.MSCC[i].appendGroup(dst)
		dst = closeGroupedAVP(dst, gOff)
	}
	if v.HasServiceInformation { // Service-Information (873, vendor 10415)
		dst, gOff = openGroupedAVP(dst, 873, 0xc0, 10415)
		dst = v.ServiceInformation.appendGroup(dst)
		dst = closeGroupedAVP(dst, gOff)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools CCR values).
func (v *CCR) Reset() {
	v.Hdr = Header{}
	v.SessionID = nil
	v.OriginHost = nil
	v.OriginRealm = nil
	v.DestinationRealm = nil
	v.AuthApplicationID = 0
	v.HasAuthApplicationID = false
	v.ServiceContextID = nil
	v.CCRequestType = 0
	v.HasCCRequestType = false
	v.CCRequestNumber = 0
	v.HasCCRequestNumber = false
	v.DestinationHost = nil
	v.SubscriptionID = v.SubscriptionID[:0]
	v.UserEquipmentInfo.Reset()
	v.HasUserEquipmentInfo = false
	v.TerminationCause = 0
	v.HasTerminationCause = false
	v.OriginStateID = 0
	v.HasOriginStateID = false
	v.EventTimestamp = 0
	v.HasEventTimestamp = false
	v.MSCC = v.MSCC[:0]
	v.ServiceInformation.Reset()
	v.HasServiceInformation = false
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *CCR) Clone() *CCR {
	c := *v
	c.SessionID = append([]byte(nil), v.SessionID...)
	c.OriginHost = append([]byte(nil), v.OriginHost...)
	c.OriginRealm = append([]byte(nil), v.OriginRealm...)
	c.DestinationRealm = append([]byte(nil), v.DestinationRealm...)
	c.ServiceContextID = append([]byte(nil), v.ServiceContextID...)
	c.DestinationHost = append([]byte(nil), v.DestinationHost...)
	if v.SubscriptionID != nil {
		c.SubscriptionID = make([]SubscriptionID, len(v.SubscriptionID))
		for i := range v.SubscriptionID {
			c.SubscriptionID[i] = *v.SubscriptionID[i].Clone()
		}
	}
	c.UserEquipmentInfo = *v.UserEquipmentInfo.Clone()
	if v.MSCC != nil {
		c.MSCC = make([]MSCC, len(v.MSCC))
		for i := range v.MSCC {
			c.MSCC[i] = *v.MSCC[i].Clone()
		}
	}
	c.ServiceInformation = *v.ServiceInformation.Clone()
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}

// ParseFrom decodes a complete Diameter message (including the
// 20-byte header) into m. It never panics on malformed input.
func (m *CCR) ParseFrom(buf []byte) error {
	m.Reset()
	h, err := ParseHeader(buf)
	if err != nil {
		return err
	}
	if h.CommandCode != 272 {
		return ErrUnexpectedCommand
	}
	m.Hdr = h
	return m.parseGroup(buf[HeaderLength:])
}

// AppendTo serializes m append-style (like strconv.Append*) so the
// caller controls buffer reuse. Command code and application id are
// fixed (272/4); flags and hop/end ids come from m.Hdr. Message and
// grouped lengths are reserve-and-backpatched in a single pass.
func (m *CCR) AppendTo(dst []byte) []byte {
	msgOff := len(dst)
	h := m.Hdr
	h.CommandCode = 272
	h.ApplicationID = 4
	dst = appendHeader(dst, h)
	dst = m.appendGroup(dst)
	backpatchMessageLength(dst, msgOff)
	return dst
}
