// Code generated by gycodegen; DO NOT EDIT.
// Source of truth: dictionary XML under diam/dict/testdata, filtered by
// the allowlist in cmd/gycodegen/model.go.

package gycodec

// cloneRawAVPs deep-copies a RawAVP slice.
func cloneRawAVPs(in []RawAVP) []RawAVP {
	if in == nil {
		return nil
	}
	out := make([]RawAVP, len(in))
	for i := range in {
		out[i] = in[i].clone()
	}
	return out
}

// SubscriptionID is the Subscription-Id grouped AVP (RFC 4006).
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type SubscriptionID struct {
	Type    int32 // Subscription-Id-Type (450)
	HasType bool
	Data    []byte // Subscription-Id-Data (444)

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *SubscriptionID) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 450 && vendorID == 0: // Subscription-Id-Type (450)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.Type = int32(be32(data))
			v.HasType = true
		case code == 444 && vendorID == 0: // Subscription-Id-Data (444)
			v.Data = data
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *SubscriptionID) appendGroup(dst []byte) []byte {
	if v.HasType { // Subscription-Id-Type (450)
		dst = appendAVPInt32(dst, 450, 0x40, 0, v.Type)
	}
	if v.Data != nil { // Subscription-Id-Data (444)
		dst = appendAVPBytes(dst, 444, 0x40, 0, v.Data)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools SubscriptionID values).
func (v *SubscriptionID) Reset() {
	v.Type = 0
	v.HasType = false
	v.Data = nil
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *SubscriptionID) Clone() *SubscriptionID {
	c := *v
	c.Data = append([]byte(nil), v.Data...)
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}

// UserEquipmentInfo is the User-Equipment-Info grouped AVP (RFC 4006).
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type UserEquipmentInfo struct {
	Type    int32 // User-Equipment-Info-Type (459)
	HasType bool
	Value   []byte // User-Equipment-Info-Value (460)

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *UserEquipmentInfo) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 459 && vendorID == 0: // User-Equipment-Info-Type (459)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.Type = int32(be32(data))
			v.HasType = true
		case code == 460 && vendorID == 0: // User-Equipment-Info-Value (460)
			v.Value = data
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *UserEquipmentInfo) appendGroup(dst []byte) []byte {
	if v.HasType { // User-Equipment-Info-Type (459)
		dst = appendAVPInt32(dst, 459, 0x00, 0, v.Type)
	}
	if v.Value != nil { // User-Equipment-Info-Value (460)
		dst = appendAVPBytes(dst, 460, 0x00, 0, v.Value)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools UserEquipmentInfo values).
func (v *UserEquipmentInfo) Reset() {
	v.Type = 0
	v.HasType = false
	v.Value = nil
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *UserEquipmentInfo) Clone() *UserEquipmentInfo {
	c := *v
	c.Value = append([]byte(nil), v.Value...)
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}

// RequestedServiceUnit is the Requested-Service-Unit grouped AVP (RFC 4006).
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type RequestedServiceUnit struct {
	CCTime                    uint32 // CC-Time (420)
	HasCCTime                 bool
	CCTotalOctets             uint64 // CC-Total-Octets (421)
	HasCCTotalOctets          bool
	CCInputOctets             uint64 // CC-Input-Octets (412)
	HasCCInputOctets          bool
	CCOutputOctets            uint64 // CC-Output-Octets (414)
	HasCCOutputOctets         bool
	CCServiceSpecificUnits    uint64 // CC-Service-Specific-Units (417)
	HasCCServiceSpecificUnits bool

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *RequestedServiceUnit) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 420 && vendorID == 0: // CC-Time (420)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.CCTime = be32(data)
			v.HasCCTime = true
		case code == 421 && vendorID == 0: // CC-Total-Octets (421)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCTotalOctets = be64(data)
			v.HasCCTotalOctets = true
		case code == 412 && vendorID == 0: // CC-Input-Octets (412)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCInputOctets = be64(data)
			v.HasCCInputOctets = true
		case code == 414 && vendorID == 0: // CC-Output-Octets (414)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCOutputOctets = be64(data)
			v.HasCCOutputOctets = true
		case code == 417 && vendorID == 0: // CC-Service-Specific-Units (417)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCServiceSpecificUnits = be64(data)
			v.HasCCServiceSpecificUnits = true
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *RequestedServiceUnit) appendGroup(dst []byte) []byte {
	if v.HasCCTime { // CC-Time (420)
		dst = appendAVPUint32(dst, 420, 0x40, 0, v.CCTime)
	}
	if v.HasCCTotalOctets { // CC-Total-Octets (421)
		dst = appendAVPUint64(dst, 421, 0x40, 0, v.CCTotalOctets)
	}
	if v.HasCCInputOctets { // CC-Input-Octets (412)
		dst = appendAVPUint64(dst, 412, 0x40, 0, v.CCInputOctets)
	}
	if v.HasCCOutputOctets { // CC-Output-Octets (414)
		dst = appendAVPUint64(dst, 414, 0x40, 0, v.CCOutputOctets)
	}
	if v.HasCCServiceSpecificUnits { // CC-Service-Specific-Units (417)
		dst = appendAVPUint64(dst, 417, 0x40, 0, v.CCServiceSpecificUnits)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools RequestedServiceUnit values).
func (v *RequestedServiceUnit) Reset() {
	v.CCTime = 0
	v.HasCCTime = false
	v.CCTotalOctets = 0
	v.HasCCTotalOctets = false
	v.CCInputOctets = 0
	v.HasCCInputOctets = false
	v.CCOutputOctets = 0
	v.HasCCOutputOctets = false
	v.CCServiceSpecificUnits = 0
	v.HasCCServiceSpecificUnits = false
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *RequestedServiceUnit) Clone() *RequestedServiceUnit {
	c := *v
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}

// GrantedServiceUnit is the Granted-Service-Unit grouped AVP (RFC 4006).
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type GrantedServiceUnit struct {
	CCTime                    uint32 // CC-Time (420)
	HasCCTime                 bool
	CCTotalOctets             uint64 // CC-Total-Octets (421)
	HasCCTotalOctets          bool
	CCInputOctets             uint64 // CC-Input-Octets (412)
	HasCCInputOctets          bool
	CCOutputOctets            uint64 // CC-Output-Octets (414)
	HasCCOutputOctets         bool
	CCServiceSpecificUnits    uint64 // CC-Service-Specific-Units (417)
	HasCCServiceSpecificUnits bool

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *GrantedServiceUnit) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 420 && vendorID == 0: // CC-Time (420)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.CCTime = be32(data)
			v.HasCCTime = true
		case code == 421 && vendorID == 0: // CC-Total-Octets (421)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCTotalOctets = be64(data)
			v.HasCCTotalOctets = true
		case code == 412 && vendorID == 0: // CC-Input-Octets (412)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCInputOctets = be64(data)
			v.HasCCInputOctets = true
		case code == 414 && vendorID == 0: // CC-Output-Octets (414)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCOutputOctets = be64(data)
			v.HasCCOutputOctets = true
		case code == 417 && vendorID == 0: // CC-Service-Specific-Units (417)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCServiceSpecificUnits = be64(data)
			v.HasCCServiceSpecificUnits = true
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *GrantedServiceUnit) appendGroup(dst []byte) []byte {
	if v.HasCCTime { // CC-Time (420)
		dst = appendAVPUint32(dst, 420, 0x40, 0, v.CCTime)
	}
	if v.HasCCTotalOctets { // CC-Total-Octets (421)
		dst = appendAVPUint64(dst, 421, 0x40, 0, v.CCTotalOctets)
	}
	if v.HasCCInputOctets { // CC-Input-Octets (412)
		dst = appendAVPUint64(dst, 412, 0x40, 0, v.CCInputOctets)
	}
	if v.HasCCOutputOctets { // CC-Output-Octets (414)
		dst = appendAVPUint64(dst, 414, 0x40, 0, v.CCOutputOctets)
	}
	if v.HasCCServiceSpecificUnits { // CC-Service-Specific-Units (417)
		dst = appendAVPUint64(dst, 417, 0x40, 0, v.CCServiceSpecificUnits)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools GrantedServiceUnit values).
func (v *GrantedServiceUnit) Reset() {
	v.CCTime = 0
	v.HasCCTime = false
	v.CCTotalOctets = 0
	v.HasCCTotalOctets = false
	v.CCInputOctets = 0
	v.HasCCInputOctets = false
	v.CCOutputOctets = 0
	v.HasCCOutputOctets = false
	v.CCServiceSpecificUnits = 0
	v.HasCCServiceSpecificUnits = false
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *GrantedServiceUnit) Clone() *GrantedServiceUnit {
	c := *v
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}

// UsedServiceUnit is the Used-Service-Unit grouped AVP (RFC 4006).
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type UsedServiceUnit struct {
	TariffChangeUsage         int32 // Tariff-Change-Usage (452)
	HasTariffChangeUsage      bool
	CCTime                    uint32 // CC-Time (420)
	HasCCTime                 bool
	CCTotalOctets             uint64 // CC-Total-Octets (421)
	HasCCTotalOctets          bool
	CCInputOctets             uint64 // CC-Input-Octets (412)
	HasCCInputOctets          bool
	CCOutputOctets            uint64 // CC-Output-Octets (414)
	HasCCOutputOctets         bool
	CCServiceSpecificUnits    uint64 // CC-Service-Specific-Units (417)
	HasCCServiceSpecificUnits bool

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *UsedServiceUnit) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 452 && vendorID == 0: // Tariff-Change-Usage (452)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.TariffChangeUsage = int32(be32(data))
			v.HasTariffChangeUsage = true
		case code == 420 && vendorID == 0: // CC-Time (420)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.CCTime = be32(data)
			v.HasCCTime = true
		case code == 421 && vendorID == 0: // CC-Total-Octets (421)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCTotalOctets = be64(data)
			v.HasCCTotalOctets = true
		case code == 412 && vendorID == 0: // CC-Input-Octets (412)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCInputOctets = be64(data)
			v.HasCCInputOctets = true
		case code == 414 && vendorID == 0: // CC-Output-Octets (414)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCOutputOctets = be64(data)
			v.HasCCOutputOctets = true
		case code == 417 && vendorID == 0: // CC-Service-Specific-Units (417)
			if len(data) != 8 {
				return ErrBadAVPData
			}
			v.CCServiceSpecificUnits = be64(data)
			v.HasCCServiceSpecificUnits = true
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *UsedServiceUnit) appendGroup(dst []byte) []byte {
	if v.HasTariffChangeUsage { // Tariff-Change-Usage (452)
		dst = appendAVPInt32(dst, 452, 0x40, 0, v.TariffChangeUsage)
	}
	if v.HasCCTime { // CC-Time (420)
		dst = appendAVPUint32(dst, 420, 0x40, 0, v.CCTime)
	}
	if v.HasCCTotalOctets { // CC-Total-Octets (421)
		dst = appendAVPUint64(dst, 421, 0x40, 0, v.CCTotalOctets)
	}
	if v.HasCCInputOctets { // CC-Input-Octets (412)
		dst = appendAVPUint64(dst, 412, 0x40, 0, v.CCInputOctets)
	}
	if v.HasCCOutputOctets { // CC-Output-Octets (414)
		dst = appendAVPUint64(dst, 414, 0x40, 0, v.CCOutputOctets)
	}
	if v.HasCCServiceSpecificUnits { // CC-Service-Specific-Units (417)
		dst = appendAVPUint64(dst, 417, 0x40, 0, v.CCServiceSpecificUnits)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools UsedServiceUnit values).
func (v *UsedServiceUnit) Reset() {
	v.TariffChangeUsage = 0
	v.HasTariffChangeUsage = false
	v.CCTime = 0
	v.HasCCTime = false
	v.CCTotalOctets = 0
	v.HasCCTotalOctets = false
	v.CCInputOctets = 0
	v.HasCCInputOctets = false
	v.CCOutputOctets = 0
	v.HasCCOutputOctets = false
	v.CCServiceSpecificUnits = 0
	v.HasCCServiceSpecificUnits = false
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *UsedServiceUnit) Clone() *UsedServiceUnit {
	c := *v
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}

// FinalUnitIndication is the Final-Unit-Indication grouped AVP (RFC 4006). Restriction filter rules and redirect servers fall into Other.
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type FinalUnitIndication struct {
	FinalUnitAction    int32 // Final-Unit-Action (449)
	HasFinalUnitAction bool

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *FinalUnitIndication) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 449 && vendorID == 0: // Final-Unit-Action (449)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.FinalUnitAction = int32(be32(data))
			v.HasFinalUnitAction = true
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *FinalUnitIndication) appendGroup(dst []byte) []byte {
	if v.HasFinalUnitAction { // Final-Unit-Action (449)
		dst = appendAVPInt32(dst, 449, 0x40, 0, v.FinalUnitAction)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools FinalUnitIndication values).
func (v *FinalUnitIndication) Reset() {
	v.FinalUnitAction = 0
	v.HasFinalUnitAction = false
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *FinalUnitIndication) Clone() *FinalUnitIndication {
	c := *v
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}

// Trigger is the 3GPP Trigger grouped AVP (TS 32.299).
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type Trigger struct {
	TriggerType []int32 // Trigger-Type (870, vendor 10415)

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *Trigger) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 870 && vendorID == 10415: // Trigger-Type (870, vendor 10415)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.TriggerType = append(v.TriggerType, int32(be32(data)))
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *Trigger) appendGroup(dst []byte) []byte {
	for _, e := range v.TriggerType { // Trigger-Type (870, vendor 10415)
		dst = appendAVPInt32(dst, 870, 0xc0, 10415, e)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools Trigger values).
func (v *Trigger) Reset() {
	v.TriggerType = v.TriggerType[:0]
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *Trigger) Clone() *Trigger {
	c := *v
	c.TriggerType = append([]int32(nil), v.TriggerType...)
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}

// PSInformation is the 3GPP PS-Information grouped AVP (TS 32.299). Only the OCS-relevant subset is modeled; the rest falls into Other.
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type PSInformation struct {
	TGPPChargingID  []byte // TGPP-Charging-Id (2, vendor 10415)
	TGPPPDPType     int32  // TGPP-PDP-Type (3, vendor 10415)
	HasTGPPPDPType  bool
	SGSNAddress     []byte // SGSN-Address (1228, vendor 10415)
	GGSNAddress     []byte // GGSN-Address (847, vendor 10415)
	CalledStationID []byte // Called-Station-Id (30)
	TGPPRATType     []byte // TGPP-RAT-Type (21, vendor 10415)

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *PSInformation) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 2 && vendorID == 10415: // TGPP-Charging-Id (2, vendor 10415)
			v.TGPPChargingID = data
		case code == 3 && vendorID == 10415: // TGPP-PDP-Type (3, vendor 10415)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.TGPPPDPType = int32(be32(data))
			v.HasTGPPPDPType = true
		case code == 1228 && vendorID == 10415: // SGSN-Address (1228, vendor 10415)
			v.SGSNAddress = data
		case code == 847 && vendorID == 10415: // GGSN-Address (847, vendor 10415)
			v.GGSNAddress = data
		case code == 30 && vendorID == 0: // Called-Station-Id (30)
			v.CalledStationID = data
		case code == 21 && vendorID == 10415: // TGPP-RAT-Type (21, vendor 10415)
			v.TGPPRATType = data
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *PSInformation) appendGroup(dst []byte) []byte {
	if v.TGPPChargingID != nil { // TGPP-Charging-Id (2, vendor 10415)
		dst = appendAVPBytes(dst, 2, 0x80, 10415, v.TGPPChargingID)
	}
	if v.HasTGPPPDPType { // TGPP-PDP-Type (3, vendor 10415)
		dst = appendAVPInt32(dst, 3, 0x80, 10415, v.TGPPPDPType)
	}
	if v.SGSNAddress != nil { // SGSN-Address (1228, vendor 10415)
		dst = appendAVPBytes(dst, 1228, 0xc0, 10415, v.SGSNAddress)
	}
	if v.GGSNAddress != nil { // GGSN-Address (847, vendor 10415)
		dst = appendAVPBytes(dst, 847, 0xc0, 10415, v.GGSNAddress)
	}
	if v.CalledStationID != nil { // Called-Station-Id (30)
		dst = appendAVPBytes(dst, 30, 0x40, 0, v.CalledStationID)
	}
	if v.TGPPRATType != nil { // TGPP-RAT-Type (21, vendor 10415)
		dst = appendAVPBytes(dst, 21, 0x80, 10415, v.TGPPRATType)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools PSInformation values).
func (v *PSInformation) Reset() {
	v.TGPPChargingID = nil
	v.TGPPPDPType = 0
	v.HasTGPPPDPType = false
	v.SGSNAddress = nil
	v.GGSNAddress = nil
	v.CalledStationID = nil
	v.TGPPRATType = nil
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *PSInformation) Clone() *PSInformation {
	c := *v
	c.TGPPChargingID = append([]byte(nil), v.TGPPChargingID...)
	c.SGSNAddress = append([]byte(nil), v.SGSNAddress...)
	c.GGSNAddress = append([]byte(nil), v.GGSNAddress...)
	c.CalledStationID = append([]byte(nil), v.CalledStationID...)
	c.TGPPRATType = append([]byte(nil), v.TGPPRATType...)
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}

// ServiceInformation is the 3GPP Service-Information grouped AVP (TS 32.299).
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type ServiceInformation struct {
	PSInformation    PSInformation // PS-Information (874, vendor 10415)
	HasPSInformation bool

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *ServiceInformation) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 874 && vendorID == 10415: // PS-Information (874, vendor 10415)
			v.PSInformation.Reset()
			if err := v.PSInformation.parseGroup(data); err != nil {
				return err
			}
			v.HasPSInformation = true
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *ServiceInformation) appendGroup(dst []byte) []byte {
	var gOff int
	if v.HasPSInformation { // PS-Information (874, vendor 10415)
		dst, gOff = openGroupedAVP(dst, 874, 0xc0, 10415)
		dst = v.PSInformation.appendGroup(dst)
		dst = closeGroupedAVP(dst, gOff)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools ServiceInformation values).
func (v *ServiceInformation) Reset() {
	v.PSInformation.Reset()
	v.HasPSInformation = false
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *ServiceInformation) Clone() *ServiceInformation {
	c := *v
	c.PSInformation = *v.PSInformation.Clone()
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}

// MSCC is the Multiple-Services-Credit-Control grouped AVP (RFC 4006).
//
// OWNERSHIP: all []byte fields (including RawAVP data) alias the read
// buffer passed to ParseFrom and are valid ONLY until the handler
// returns. Use Clone() to retain data beyond that point.
type MSCC struct {
	RatingGroup            uint32 // Rating-Group (432)
	HasRatingGroup         bool
	ServiceIdentifier      uint32 // Service-Identifier (439)
	HasServiceIdentifier   bool
	Requested              RequestedServiceUnit // Requested-Service-Unit (437)
	HasRequested           bool
	Used                   []UsedServiceUnit  // Used-Service-Unit (446)
	Granted                GrantedServiceUnit // Granted-Service-Unit (431)
	HasGranted             bool
	ValidityTime           uint32 // Validity-Time (448)
	HasValidityTime        bool
	FinalUnitIndication    FinalUnitIndication // Final-Unit-Indication (430)
	HasFinalUnitIndication bool
	Trigger                Trigger // Trigger (1264, vendor 10415)
	HasTrigger             bool
	TariffTimeChange       uint32 // Tariff-Time-Change (451)
	HasTariffTimeChange    bool
	ResultCode             uint32 // Result-Code (268)
	HasResultCode          bool

	// UnsupportedMandatory surfaces unknown AVPs carrying the M-bit
	// (RFC 6733 §5.3.1) so a handler can answer DIAMETER_AVP_UNSUPPORTED
	// with Failed-AVP; entries also appear in Other.
	UnsupportedMandatory []RawAVP
	// Other preserves all unknown AVPs in arrival order; AppendTo
	// re-emits them after the modeled fields.
	Other []RawAVP
}

// parseGroup decodes a sequence of AVPs into v. The caller must
// have Reset() v (ParseFrom does).
func (v *MSCC) parseGroup(buf []byte) error {
	for off := 0; off < len(buf); {
		code, flags, vendorID, data, next, err := walkAVP(buf, off)
		if err != nil {
			return err
		}
		switch {
		case code == 432 && vendorID == 0: // Rating-Group (432)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.RatingGroup = be32(data)
			v.HasRatingGroup = true
		case code == 439 && vendorID == 0: // Service-Identifier (439)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.ServiceIdentifier = be32(data)
			v.HasServiceIdentifier = true
		case code == 437 && vendorID == 0: // Requested-Service-Unit (437)
			v.Requested.Reset()
			if err := v.Requested.parseGroup(data); err != nil {
				return err
			}
			v.HasRequested = true
		case code == 446 && vendorID == 0: // Used-Service-Unit (446)
			if cap(v.Used) > len(v.Used) {
				v.Used = v.Used[:len(v.Used)+1]
				v.Used[len(v.Used)-1].Reset()
			} else {
				v.Used = append(v.Used, UsedServiceUnit{})
			}
			if err := v.Used[len(v.Used)-1].parseGroup(data); err != nil {
				return err
			}
		case code == 431 && vendorID == 0: // Granted-Service-Unit (431)
			v.Granted.Reset()
			if err := v.Granted.parseGroup(data); err != nil {
				return err
			}
			v.HasGranted = true
		case code == 448 && vendorID == 0: // Validity-Time (448)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.ValidityTime = be32(data)
			v.HasValidityTime = true
		case code == 430 && vendorID == 0: // Final-Unit-Indication (430)
			v.FinalUnitIndication.Reset()
			if err := v.FinalUnitIndication.parseGroup(data); err != nil {
				return err
			}
			v.HasFinalUnitIndication = true
		case code == 1264 && vendorID == 10415: // Trigger (1264, vendor 10415)
			v.Trigger.Reset()
			if err := v.Trigger.parseGroup(data); err != nil {
				return err
			}
			v.HasTrigger = true
		case code == 451 && vendorID == 0: // Tariff-Time-Change (451)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.TariffTimeChange = be32(data)
			v.HasTariffTimeChange = true
		case code == 268 && vendorID == 0: // Result-Code (268)
			if len(data) != 4 {
				return ErrBadAVPData
			}
			v.ResultCode = be32(data)
			v.HasResultCode = true
		default:
			raw := RawAVP{Code: code, VendorID: vendorID, Flags: flags, Data: data}
			v.Other = append(v.Other, raw)
			if flags&FlagMandatory != 0 {
				v.UnsupportedMandatory = append(v.UnsupportedMandatory, raw)
			}
		}
		off = next
	}
	return nil
}

// appendGroup serializes v's AVPs in the fixed emission order
// (codec-design.md §2.6), unknown AVPs last in arrival order.
func (v *MSCC) appendGroup(dst []byte) []byte {
	var gOff int
	if v.HasRatingGroup { // Rating-Group (432)
		dst = appendAVPUint32(dst, 432, 0x40, 0, v.RatingGroup)
	}
	if v.HasServiceIdentifier { // Service-Identifier (439)
		dst = appendAVPUint32(dst, 439, 0x40, 0, v.ServiceIdentifier)
	}
	if v.HasRequested { // Requested-Service-Unit (437)
		dst, gOff = openGroupedAVP(dst, 437, 0x40, 0)
		dst = v.Requested.appendGroup(dst)
		dst = closeGroupedAVP(dst, gOff)
	}
	for i := range v.Used { // Used-Service-Unit (446)
		dst, gOff = openGroupedAVP(dst, 446, 0x40, 0)
		dst = v.Used[i].appendGroup(dst)
		dst = closeGroupedAVP(dst, gOff)
	}
	if v.HasGranted { // Granted-Service-Unit (431)
		dst, gOff = openGroupedAVP(dst, 431, 0x40, 0)
		dst = v.Granted.appendGroup(dst)
		dst = closeGroupedAVP(dst, gOff)
	}
	if v.HasValidityTime { // Validity-Time (448)
		dst = appendAVPUint32(dst, 448, 0x40, 0, v.ValidityTime)
	}
	if v.HasFinalUnitIndication { // Final-Unit-Indication (430)
		dst, gOff = openGroupedAVP(dst, 430, 0x40, 0)
		dst = v.FinalUnitIndication.appendGroup(dst)
		dst = closeGroupedAVP(dst, gOff)
	}
	if v.HasTrigger { // Trigger (1264, vendor 10415)
		dst, gOff = openGroupedAVP(dst, 1264, 0xc0, 10415)
		dst = v.Trigger.appendGroup(dst)
		dst = closeGroupedAVP(dst, gOff)
	}
	if v.HasTariffTimeChange { // Tariff-Time-Change (451)
		dst = appendAVPUint32(dst, 451, 0x40, 0, v.TariffTimeChange)
	}
	if v.HasResultCode { // Result-Code (268)
		dst = appendAVPUint32(dst, 268, 0x40, 0, v.ResultCode)
	}
	for i := range v.Other {
		dst = v.Other[i].appendTo(dst)
	}
	return dst
}

// Reset clears v for reuse, keeping slice capacity (steady-state
// zero-allocation parsing when the caller pools MSCC values).
func (v *MSCC) Reset() {
	v.RatingGroup = 0
	v.HasRatingGroup = false
	v.ServiceIdentifier = 0
	v.HasServiceIdentifier = false
	v.Requested.Reset()
	v.HasRequested = false
	v.Used = v.Used[:0]
	v.Granted.Reset()
	v.HasGranted = false
	v.ValidityTime = 0
	v.HasValidityTime = false
	v.FinalUnitIndication.Reset()
	v.HasFinalUnitIndication = false
	v.Trigger.Reset()
	v.HasTrigger = false
	v.TariffTimeChange = 0
	v.HasTariffTimeChange = false
	v.ResultCode = 0
	v.HasResultCode = false
	v.UnsupportedMandatory = v.UnsupportedMandatory[:0]
	v.Other = v.Other[:0]
}

// Clone returns a deep copy of v whose []byte fields own their
// backing arrays; safe to retain after the handler returns.
func (v *MSCC) Clone() *MSCC {
	c := *v
	c.Requested = *v.Requested.Clone()
	if v.Used != nil {
		c.Used = make([]UsedServiceUnit, len(v.Used))
		for i := range v.Used {
			c.Used[i] = *v.Used[i].Clone()
		}
	}
	c.Granted = *v.Granted.Clone()
	c.FinalUnitIndication = *v.FinalUnitIndication.Clone()
	c.Trigger = *v.Trigger.Clone()
	c.UnsupportedMandatory = cloneRawAVPs(v.UnsupportedMandatory)
	c.Other = cloneRawAVPs(v.Other)
	return &c
}
